/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/Appointments': RouteRecordInfo<'/Appointments', '/Appointments', Record<never, never>, Record<never, never>>,
    '/AppointmentsManagement': RouteRecordInfo<'/AppointmentsManagement', '/AppointmentsManagement', Record<never, never>, Record<never, never>>,
    '/Doctors': RouteRecordInfo<'/Doctors', '/Doctors', Record<never, never>, Record<never, never>>,
    '/HealthAgents': RouteRecordInfo<'/HealthAgents', '/HealthAgents', Record<never, never>, Record<never, never>>,
    '/HealthUnits': RouteRecordInfo<'/HealthUnits', '/HealthUnits', Record<never, never>, Record<never, never>>,
    '/Home': RouteRecordInfo<'/Home', '/Home', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/Patients': RouteRecordInfo<'/Patients', '/Patients', Record<never, never>, Record<never, never>>,
    '/Procedures': RouteRecordInfo<'/Procedures', '/Procedures', Record<never, never>, Record<never, never>>,
    '/ProviderUnits': RouteRecordInfo<'/ProviderUnits', '/ProviderUnits', Record<never, never>, Record<never, never>>,
    '/RequestingUnits': RouteRecordInfo<'/RequestingUnits', '/RequestingUnits', Record<never, never>, Record<never, never>>,
    '/Settings': RouteRecordInfo<'/Settings', '/Settings', Record<never, never>, Record<never, never>>,
    '/Solicitations': RouteRecordInfo<'/Solicitations', '/Solicitations', Record<never, never>, Record<never, never>>,
    '/Specialists': RouteRecordInfo<'/Specialists', '/Specialists', Record<never, never>, Record<never, never>>,
    '/Users': RouteRecordInfo<'/Users', '/Users', Record<never, never>, Record<never, never>>,
  }
}
